# docker build -f Dockerfile.digital-grid-gdal -t us.gcr.io/autogrid-pam/dev/digital-grid:v1.2.0 .
FROM docker pull thinkwhere/gdal-python

COPY requirements.txt .

# RUN conda update conda && conda env create --file conda_environment.yml # takes forever instead I 
# RUN . /opt/conda/etc/profile.d/conda.sh && conda activate python3.6 && pip install -r requirements.txt 

# COPY . digital-grid

# RUN chown -R 1001:1001 .

# USER developer