kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
    type: gp2
mountOptions:
  - debug
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  storageClassName: ebs-sc
  claimRef:
    name: data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: ebs-sc
  mountOptions:
    - hard
    - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  storageClassName: ebs-sc
  volumeName: data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

